version: '3'

vars:
  BASE_URL: 'git@github.com:p2p-energy-trading-platform'
  REPOS: 
    - gridx-infra
    - iot-simulation
    - frontend-web
    - matching-engine
    - frontend-mobile
    - protobuf
    - go-sdk
    - typescript-sdk
    - cpp-sdk
    - api-gateway
    - iot-ingestion-dispatch

tasks:
  default:
    cmds:
      - task --list
    silent: true

  setup:
    desc: "Clones any missing repositories and pulls the latest changes for existing ones."
    cmds:
      - for: { var: REPOS }
        task: clone-or-pull
        vars: { REPO: '{{.ITEM}}' }

  clone-or-pull:
    internal: true
    cmds:
      - |
        if [ -d "{{.REPO}}" ]; then
          echo "🔄 [FOUND] {{.REPO}} - Pulling latest updates..."
          git -C {{.REPO}} pull
        else
          echo "📦 [MISSING] {{.REPO}} - Cloning repository..."
          git clone {{.BASE_URL}}/{{.REPO}}.git
        fi
  build:
    desc: "Rebuild and restart specific or all containers"
    cmds:
      - docker compose -f docker-compose.root.yml up -d --build {{.CLI_ARGS}}
      
  up:
    desc: "Spin up the the entire system"
    cmds:
      - docker compose -f docker-compose.root.yml up -d

  down:
    desc: "Stop all running system containers"
    cmds:
      - docker compose -f docker-compose.root.yml down {{.CLI_ARGS}}

  infra-up:
    desc: "Spin up only gridx-infra"
    dir: gridx-infra
    cmds:
      - docker compose up -d

  infra-down:
    desc: "Stop all running gridx-infra"
    dir: gridx-infra
    cmds:
      - docker compose down

  logs:
    desc: "Tail logs for the core infrastructure containers"
    cmds:
      - docker compose -f docker-compose.root.yml logs -f {{.CLI_ARGS}}

  analyze:
    desc: "Run static complexity analysis for all GridX repositories"
    cmds:
      - bash ./scripts/complexity-analysis.sh